# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: '3'

tasks:
  start:
    cmds:
      - go run ./cmd/prism

  client:
    cmds:
      - npm run dev

  server:
    cmds:
      - go run ./cmd/prism -server -port 9999
